---
- hosts: chef
  become: yes
  tasks:
  - name: "Install common packages"
    yum:
      update_cache: yes
      name: "{{ item }}"
      state: installed
    with_items:
      - vim
      - curl
      - wget
      - git

  - name: "Install Chef"
    shell: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -c stable -v 0.18.30
  
