# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.define "chef"
  config.vm.network "public_network"
  config.vm.hostname = "chef"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.name = "chef"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "chef.yml"
  end
end
